# Generated by Django 5.0.7 on 2024-07-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_category_alter_task_options_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
