# Generated by Django 5.0.7 on 2024-09-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-stage', 'id']},
        ),
    ]
