# Generated by Django 5.0.7 on 2024-09-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task.customer'),
        ),
    ]
