# Generated by Django 5.1.2 on 2024-10-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0013_noteimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noteimage",
            old_name="image",
            new_name="image_link",
        ),
    ]
